import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:animate_do/animate_do.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:iconsax/iconsax.dart';

import '../../core/globals/profile_generator.dart';
import 'my_ai_controller.dart';

class MyAiView extends GetView<MyAiController> {
  final TextEditingController _inputCtrl = TextEditingController();
  final ScrollController _scrollController = ScrollController();



  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      body: Stack(
        children: [
          // Beautiful Elegant Background
          Positioned.fill(
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: isDark
                      ? [
                    Color(0xFF0A1F2C),
                    Color(0xFF1A3A4B),
                    Color(0xFF2C3E50),
                  ]
                      : [
                    Color(0xFF0A1F2C),
                    Color(0xFF1A3A4B),
                    Color(0xFF2C3E50),
                  ],
                  stops: [0.0, 0.5, 1.0],
                ),
              ),
              child: CustomPaint(
                painter: _BackgroundPatternPainter(isDark:false),
              ),
            ),
          ),

          // Content
          CustomScrollView(
            controller: _scrollController,
            slivers: [
              // App Bar with user info
              SliverAppBar(
                expandedHeight: 350,
                pinned: true,
                floating: true,
                backgroundColor: Colors.transparent,
                elevation: 0,
                title: Row(
                  children: [
                    _buildBotStatus(),
                    const SizedBox(width: 12),
                    FadeIn(
                      child: Container(
                        padding:
                        const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Colors.amberAccent.shade700.withOpacity(0.8),
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Row(
                          children: [
                            Text(
                              "Content generated by Soulbuddy",
                              style: GoogleFonts.poppins(
                                fontSize: 12,
                                fontWeight: FontWeight.w500,
                                color: const Color(0xFFFAFAFA),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
                flexibleSpace: _buildFlexibleSpace(isDark),
                leading: IconButton(
                  icon: Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.3),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Icon(
                      Iconsax.arrow_left_2,
                      color: const Color(0xFFD4AF37),
                      size: 24,
                    ),
                  ),
                  onPressed: () => Get.back(),
                ),
                actions: [
                  Obx(() => Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.3),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Icon(
                      controller.isConnected.value
                          ? Iconsax.wifi_square
                          : Iconsax.home_wifi,
                      color: controller.isConnected.value
                          ? const Color(0xFF4DB6AC)
                          : const Color(0xFFD4AF37),
                      size: 22,
                    ),
                  )),
                ],
              ),

              // Chat Messages
              SliverToBoxAdapter(
                child: _buildMessagesList(theme, isDark),
              ),

              // Typing Indicator
              SliverToBoxAdapter(
                child: Obx(() => controller.isTyping.value
                    ? _buildTypingIndicator(isDark)
                    : const SizedBox(height: 80)),
              ),
            ],
          ),

          // Input Bar
          Positioned(
            bottom: 0,
            left: 0,
            right: 0,
            child: _buildInputBar(theme, isDark),
          ),
        ],
      ),
    );
  }

  Widget _buildMessagesList(ThemeData theme, bool isDark) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 30),
      child: Obx(() {
        // Auto-scroll to bottom when messages update
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (_scrollController.hasClients) {
            _scrollController.animateTo(
              _scrollController.position.maxScrollExtent,
              duration: const Duration(milliseconds: 300),
              curve: Curves.easeOut,
            );
          }
        });

        final messageCount = controller.messages.length;

        return ListView.separated(
          physics: const NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          itemCount: messageCount,
          separatorBuilder: (_, index) => const SizedBox(height: 12),
          itemBuilder: (_, index) {
            final msg = controller.messages[index];
            return FadeInLeft(
              delay: Duration(milliseconds: 100),
              child: Align(
                alignment:
                msg.isAI ? Alignment.centerLeft : Alignment.centerRight,
                child: ConstrainedBox(
                  constraints: BoxConstraints(
                    maxWidth: MediaQuery.of(Get.context!).size.width * 0.8,
                  ),
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: msg.isAI
                          ? (isDark
                          ? Color(0xFF1A3A4B).withOpacity(0.9)
                          : Colors.white.withOpacity(0.9))
                          : (isDark
                          ? Color(0xFF008080).withOpacity(0.9)
                          : Color(0xFF4DB6AC).withOpacity(0.9)),
                      borderRadius: BorderRadius.only(
                        topLeft: const Radius.circular(20),
                        topRight: const Radius.circular(20),
                        bottomLeft: msg.isAI
                            ? const Radius.circular(4)
                            : const Radius.circular(20),
                        bottomRight: msg.isAI
                            ? const Radius.circular(20)
                            : const Radius.circular(4),
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.1),
                          blurRadius: 8,
                          offset: const Offset(0, 2),
                        ),
                      ],
                      border: msg.isAI
                          ? Border.all(
                        color: const Color(0xFF008080).withOpacity(0.2),
                        width: 1,
                      )
                          : null,
                    ),
                    child: Column(
                      crossAxisAlignment: msg.isAI
                          ? CrossAxisAlignment.start
                          : CrossAxisAlignment.end,
                      children: [
                        if (msg.isAI)
                          Obx(() {
                            final user = controller.user.value;
                            if (user == null) return Container();

                            return Row(
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(4),
                                  decoration: BoxDecoration(
                                    color: _getRoleColor(user.role)
                                        .withOpacity(0.2),
                                    borderRadius: BorderRadius.circular(6),
                                  ),
                                  child: Icon(
                                    _getRoleIcon(user.role),
                                    size: 14,
                                    color: _getRoleColor(user.role),
                                  ),
                                ),
                                const SizedBox(width: 8),
                                Text(
                                  user.name,
                                  style: GoogleFonts.poppins(
                                    fontSize: 12,
                                    fontWeight: FontWeight.w500,
                                    color: _getRoleColor(user.role),
                                  ),
                                ),
                              ],
                            );
                          }),
                        const SizedBox(height: 6),
                        Text(
                          msg.text,
                          style: GoogleFonts.poppins(
                            fontSize: 15,
                            color: msg.isAI
                                ? (isDark
                                ? Colors.white
                                : const Color(0xFF2C2C2C))
                                : Colors.white,
                            height: 1.4,
                          ),
                        ),
                        const SizedBox(height: 6),
                        Text(
                          "${msg.dateTime.hour}:${msg.dateTime.minute.toString().padLeft(2, '0')}",
                          style: GoogleFonts.poppins(
                            fontSize: 10,
                            color: msg.isAI
                                ? (isDark
                                ? Colors.grey[400]
                                : const Color(0xFF008080).withOpacity(0.7))
                                : Colors.white.withOpacity(0.8),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            );
          },
        );
      }),
    );
  }

  Widget _buildFlexibleSpace(bool isDark) {
    return Stack(
      children: [
        // Background Profile Image with elegant overlay
        Positioned.fill(
          child: Obx(() {
            final user = controller.user.value;
            final imageUrl =
            ProfileImageHelper.getRandomImage(user.name, user.role);

            return Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage(imageUrl),
                  fit: BoxFit.cover,
                  colorFilter: ColorFilter.mode(
                    Colors.black.withOpacity(0.3),
                    BlendMode.darken,
                  ),
                ),
              ),
              child: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [
                      Colors.black.withOpacity(0.7),
                      Colors.black.withOpacity(0.4),
                      Colors.transparent,
                    ],
                  ),
                ),
              ),
            );
          }),
        ),

        // User details overlay
        Positioned(
          left: 24,
          right: 24,
          bottom: 24,
          child: Obx(() {
            final user = controller.user.value;
            if (user == null) {
              return Container();
            }

            return FadeInLeft(
              delay: const Duration(milliseconds: 300),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Name and Role
                  Row(
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        decoration: BoxDecoration(
                          color: const Color(0xFFD4AF37),
                          shape: BoxShape.circle,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          user.name,
                          style: GoogleFonts.poppins(
                            fontSize: 24,
                            fontWeight: FontWeight.bold,
                            color: const Color(0xFFFAFAFA),
                          ),
                        ),
                      ),
                      if (user.isVerified)
                        Icon(
                          Iconsax.verify,
                          color: const Color(0xFFD4AF37),
                          size: 20,
                        ),
                    ],
                  ),
                  const SizedBox(height: 8),

                  // Role
                  Row(
                    children: [
                      const SizedBox(width: 20),
                      Container(
                        padding:
                        const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                        decoration: BoxDecoration(
                          color: _getRoleColor(user.role).withOpacity(0.3),
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: _getRoleColor(user.role),
                            width: 1,
                          ),
                        ),
                        child: Text(
                          user.role.toUpperCase(),
                          style: GoogleFonts.poppins(
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                            color: _getRoleColor(user.role),
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),

                  // User details (bio)
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 20, vertical: 12),
                    decoration: BoxDecoration(
                      color: Colors.black.withOpacity(0.5),
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(
                        color: const Color(0xFF008080).withOpacity(0.3),
                      ),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Specialization
                        if (user.specialization != null &&
                            user.specialization!.isNotEmpty)
                          _buildDetailRow(
                            icon: Iconsax.cpu,
                            text: user.specialization!,
                            color: const Color(0xFF4DB6AC),
                          ),

                        // Location
                        if (user.location != null && user.location!.isNotEmpty)
                          _buildDetailRow(
                            icon: Iconsax.location,
                            text: user.location!,
                            color: const Color(0xFF4DB6AC),
                          ),

                        // Experience
                        if (user.experience != null)
                          _buildDetailRow(
                            icon: Iconsax.calendar,
                            text: "${user.experience} years experience",
                            color: const Color(0xFF4DB6AC),
                          ),

                        // Bio
                        if (user.bio != null && user.bio!.isNotEmpty)
                          Padding(
                            padding: const EdgeInsets.only(top: 8),
                            child: Text(
                              user.bio!,
                              style: GoogleFonts.poppins(
                                fontSize: 13,
                                color:
                                const Color(0xFFE0F7FA).withOpacity(0.9),
                                height: 1.4,
                              ),
                              maxLines: 3,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                      ],
                    ),
                  ),
                ],
              ),
            );
          }),
        ),
      ],
    );
  }

  Widget _buildDetailRow({
    required IconData icon,
    required String text,
    required Color color,
  }) {
    return Padding(
        padding: const EdgeInsets.only(bottom: 6),
        child: Row(
          children: [
            Icon(
              icon,
              size: 14,
              color: color,
            ),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                text,
                style: GoogleFonts.poppins(
                  fontSize: 13,
                  color: const Color(0xFFFAFAFA),
                ),
              ),
            ),
          ],
        ));
    }


Color _getRoleColor(String role) {
  switch (role) {
    case 'therapist':
      return const Color(0xFF2DD4BF);
    case 'therapy_center':
      return const Color(0xFF0D9488);
    case 'patient':
      return const Color(0xFF134E4A);
    default:
      return const Color(0xFF0A7C8F);
  }
}

Widget _buildBotStatus() {
  return Obx(() {
    final isReady = controller.isConnected.value;
    return Bounce(
      infinite: true,
      child: Container(
        width: 14,
        height: 14,
        decoration: BoxDecoration(
          color: isReady ? const Color(0xFF4DB6AC) : const Color(0xFFD4AF37),
          shape: BoxShape.circle,
          boxShadow: [
            BoxShadow(
              color: isReady
                  ? const Color(0xFF4DB6AC).withOpacity(0.5)
                  : const Color(0xFFD4AF37).withOpacity(0.5),
              blurRadius: 8,
              spreadRadius: 2,
            ),
          ],
        ),
      ),
    );
  });
}

IconData _getRoleIcon(String role) {
  switch (role) {
    case 'therapist':
      return Iconsax.health;
    case 'therapy_center':
      return Iconsax.building;
    case 'patient':
      return Iconsax.profile_2user;
    default:
      return Iconsax.user;
  }
}

Widget _buildTypingIndicator(bool isDark) {
  return FadeIn(
    child: Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isDark
                  ? Color(0xFF1A3A4B).withOpacity(0.9)
                  : Colors.white.withOpacity(0.9),
              borderRadius: BorderRadius.circular(20),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.1),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ],
              border: Border.all(
                color: const Color(0xFF008080).withOpacity(0.1),
              ),
            ),
            child: Row(
              children: [
                _typingDot(isDark, delay: 0),
                _typingDot(isDark, delay: 200),
                _typingDot(isDark, delay: 400),
              ],
            ),
          ),
          const SizedBox(width: 8),
          Obx(() {
            final user = controller.user.value;
            return Text(
              "${user?.name ?? 'AI Assistant'} is typing...",
              style: GoogleFonts.poppins(
                fontSize: 14,
                color: const Color(0xFF008080),
              ),
            );
          }),
        ],
      ),
    ),
  );
}

Widget _typingDot(bool isDark, {int delay = 0}) {
  return Pulse(
    duration: const Duration(milliseconds: 1200),
    delay: Duration(milliseconds: delay),
    infinite: true,
    child: Container(
      width: 8,
      height: 8,
      margin: const EdgeInsets.symmetric(horizontal: 2),
      decoration: BoxDecoration(
        color: const Color(0xFF4DB6AC),
        shape: BoxShape.circle,
      ),
    ),
  );
}

Widget _buildInputBar(ThemeData theme, bool isDark) {
  return SlideInUp(
    child: Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: isDark
            ? Color(0xFF1A3A4B).withOpacity(0.95)
            : Color(0xFF1A3A4B).withOpacity(0.95),
        border: Border(
          top: BorderSide(
            color: const Color(0xFF008080).withOpacity(0.1),
          ),
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 20,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      child: Row(
        children: [
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                color: isDark
                    ? Color(0xFF0A1F2C).withOpacity(0.8)
                    : Color(0xFF0A1F2C).withOpacity(0.8),
                borderRadius: BorderRadius.circular(25),
                border: Border.all(
                  color: const Color(0xFF008080).withOpacity(0.2),
                  width: 1,
                ),
                boxShadow: [
                  BoxShadow(
                    color: const Color(0xFF008080).withOpacity(0.1),
                    blurRadius: 10,
                    offset: const Offset(0, 2),
                  ),
                ],
              ),
              child: Obx(() {
                final canSend = controller.canSendMessage;
                return TextField(
                  controller: _inputCtrl,
                  enabled: canSend,
                  style: GoogleFonts.poppins(
                    color: isDark
                        ? const Color(0xFFFAFAFA)
                        : const Color(0xFFFAFAFA),
                  ),
                  decoration: InputDecoration(
                    contentPadding: const EdgeInsets.symmetric(
                      horizontal: 20,
                      vertical: 16,
                    ),
                    hintText: controller.canSendMessage
                        ? "Message ${controller.user.value?.name ?? 'AI Assistant'}..."
                        : (controller.isConnected.value
                        ? "Waiting for response..."
                        : "Connecting..."),
                    hintStyle: GoogleFonts.poppins(
                      color: isDark
                          ? const Color(0xFF4DB6AC).withOpacity(0.7)
                          : const Color(0xFF008080).withOpacity(0.7),
                    ),
                    border: InputBorder.none,
                    prefixIcon: Icon(
                      Iconsax.message,
                      color: canSend
                          ? const Color(0xFF008080)
                          : Colors.grey.withOpacity(0.5),
                    ),
                  ),
                  onSubmitted: (value) => _sendMessage(),
                );
              }),
            ),
          ),
          const SizedBox(width: 12),
          Obx(() {
            final canSend = controller.canSendMessage;
            final isConnected = controller.isConnected.value;

            return Container(
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: canSend
                    ? const LinearGradient(
                  colors: [Color(0xFF008080), Color(0xFF004D4D)],
                )
                    : LinearGradient(
                  colors: [
                    Colors.grey.withOpacity(0.3),
                    Colors.grey.withOpacity(0.1)
                  ],
                ),
                boxShadow: canSend
                    ? [
                  BoxShadow(
                    color: const Color(0xFF008080).withOpacity(0.3),
                    blurRadius: 10,
                    spreadRadius: 2,
                  ),
                ]
                    : null,
              ),
              child: IconButton(
                icon: Icon(
                  Iconsax.send_1,
                  color: canSend
                      ? const Color(0xFFFAFAFA)
                      : Colors.grey.withOpacity(0.5),
                  size: 24,
                ),
                onPressed: canSend ? _sendMessage : null,
                tooltip: canSend
                    ? "Send message"
                    : (isConnected
                    ? "Response in progress"
                    : "Not connected"),
              ),
            );
          }),
        ],
      ),
    ),
  );
}

void _sendMessage() {
  if (_inputCtrl.text.trim().isNotEmpty && controller.canSendMessage) {
    controller.sendUserMessage(_inputCtrl.text);
    _inputCtrl.clear();
  }
}
}

// Move the BackgroundPatternPainter class outside of MyAiView
class _BackgroundPatternPainter extends CustomPainter {
  final bool isDark;

  _BackgroundPatternPainter({required this.isDark});

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = isDark
          ? Color(0xFF1A3A4B).withOpacity(0.05)
          : Colors.teal.shade50.withOpacity(0.03);

    // Draw subtle grid pattern
    final gridSize = 40.0;
    for (double x = 0; x < size.width; x += gridSize) {
      canvas.drawLine(
        Offset(x, 0),
        Offset(x, size.height),
        paint,
      );
    }
    for (double y = 0; y < size.height; y += gridSize) {
      canvas.drawLine(
        Offset(0, y),
        Offset(size.width, y),
        paint,
      );
    }

    // Draw subtle circles
    final circlePaint = Paint()
      ..color = isDark
          ? Color(0xFF4DB6AC).withOpacity(0.02)
          : Colors.white70.withOpacity(0.02);

    for (int i = 0; i < 5; i++) {
      final x = size.width * (i + 1) / 6;
      final y = size.height * (i + 1) / 6;
      final radius = 100 + i * 40;
      canvas.drawCircle(Offset(x, y), radius.toDouble(), circlePaint);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}