// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBXoQeT6M8cYTgXDaNeSeWJnm2K98j_A',
    appId: '1:130407171862:web:b6b5e393ea81fa4dbdf237',
    messagingSenderId: '130407171862',
    projectId: 'ai-interview-d54b7',
    authDomain: 'ai-interview-d54b7.firebaseapp.com',
    storageBucket: 'ai-interview-d54b7.firebasestorage.app',
    measurementId: 'G-CE71LLT09D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrZM9c2x7lzpuNAtHeo6b1bzXYEoVfhxU',
    appId: '1:130407171862:android:d84c7dbac9301771bdf237',
    messagingSenderId: '130407171862',
    projectId: 'ai-interview-d54b7',
    storageBucket: 'ai-interview-d54b7.firebasestorage.app',
  );
}
